DROP TABLE IF EXISTS rumour_events;
DROP TABLE IF EXISTS rumours;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS sources;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS clubs;
DROP TYPE IF EXISTS rumour_status;
