INSERT INTO leagues (name, short_name) VALUES
    ('Argentine Primera División', 'LPF'),
    ('Brasileirão Série A', 'BSA'),
    ('Bundesliga', 'BL'),
    ('Eredivisie', 'ERE'),
    ('La Liga', 'LL'),
    ('Liga Portugal', 'LP'),
    ('Ligue 1', 'L1'),
    ('Major League Soccer', 'MLS'),
    ('Premier League', 'PL'),
    ('Saudi Pro League', 'SPL'),
    ('Scottish Premiership', 'SPFL'),
    ('Serie A', 'SA')
ON CONFLICT (lower(name)) DO UPDATE
SET name = EXCLUDED.name,
    short_name = EXCLUDED.short_name;

INSERT INTO clubs (name, short_name, crest_url, league_id)
SELECT c.name, c.short_name, NULLIF(c.crest_url, ''), l.id
FROM (VALUES
    ('Aldosivi', 'ALD', '', 'Argentine Primera División'),
    ('Argentinos Juniors', 'ARG', 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Asociaci%C3%B3n_Atl%C3%A9tica_Argentinos_Juniors_logo.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Atlético Tucumán', 'ATU', 'https://upload.wikimedia.org/wikipedia/commons/9/92/Atletico_tucuman_nuevo2.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Banfield', 'BAN', 'https://upload.wikimedia.org/wikipedia/commons/1/16/CA_Banfield_%282014%29.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Barracas Central', 'BAR', 'https://upload.wikimedia.org/wikipedia/commons/9/99/Barracas_central_logo.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Belgrano', 'BEL', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Club_Atl%C3%A9tico_Belgrano_2026.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Boca Juniors', 'BOC', 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Boca_Juniors_logo18.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Central Córdoba', 'CCO', 'https://upload.wikimedia.org/wikipedia/commons/9/92/Central_Cordoba_SdE_crest_%282025%29.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Defensa y Justicia', 'DYJ', 'https://upload.wikimedia.org/wikipedia/commons/7/70/Escudo_del_Club_Social_y_Deportivo_Defensa_y_Justicia.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Deportivo Riestra', 'RIE', 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Escudo_del_Club_Deportivo_Riestra.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Estudiantes', 'EST', 'https://upload.wikimedia.org/wikipedia/commons/1/15/Estudiantes_de_la_Plata_crest_%282025%29_cropped.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Estudiantes de Río Cuarto', 'ERC', 'https://upload.wikimedia.org/wikipedia/commons/2/20/Escudo_Asociacion_Atl%C3%A9tica_Estudiantes_de_R%C3%ADo_Cuarto.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Gimnasia y Esgrima La Plata', 'GLP', 'https://upload.wikimedia.org/wikipedia/en/6/6d/Gimnasia_Esgrima_LP_logo.svg?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=original', 'Argentine Primera División'),
    ('Gimnasia y Esgrima de Mendoza', 'GME', 'https://upload.wikimedia.org/wikipedia/commons/9/90/Escudo_Club_Atl%C3%A9tico_Gimnasia_y_Esgrima_Mendoza.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Huracán', 'HUR', 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Emblema_oficial_del_Club_Atl%C3%A9tico_Hurac%C3%A1n.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Independiente', 'IND', 'https://upload.wikimedia.org/wikipedia/commons/d/db/Escudo_del_Club_Atl%C3%A9tico_Independiente.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Independiente Rivadavia', 'IRI', 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Escudo_del_Club_Independiente_Rivadavia.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Argentine Primera División'),
    ('Instituto', 'INS', '', 'Argentine Primera División'),
    ('Lanús', 'LAN', '', 'Argentine Primera División'),
    ('Newell''s Old Boys', 'NOB', '', 'Argentine Primera División'),
    ('Platense', 'PLA', '', 'Argentine Primera División'),
    ('Racing Club', 'RAC', '', 'Argentine Primera División'),
    ('River Plate', 'RIV', '', 'Argentine Primera División'),
    ('Rosario Central', 'ROS', '', 'Argentine Primera División'),
    ('San Lorenzo', 'SLO', '', 'Argentine Primera División'),
    ('Sarmiento', 'SAR', '', 'Argentine Primera División'),
    ('Talleres', 'TAL', '', 'Argentine Primera División'),
    ('Tigre', 'TIG', '', 'Argentine Primera División'),
    ('Unión', 'UNI', '', 'Argentine Primera División'),
    ('Vélez Sarsfield', 'VEL', '', 'Argentine Primera División'),
    ('Athletico Paranaense', 'CAP', '', 'Brasileirão Série A'),
    ('Atlético Mineiro', 'CAM', 'https://upload.wikimedia.org/wikipedia/commons/2/27/Clube_Atl%C3%A9tico_Mineiro_logo.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Brasileirão Série A'),
    ('Bahia', 'BAH', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Esporte_Clube_Bahia_logo.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Brasileirão Série A'),
    ('Botafogo', 'BOT', '', 'Brasileirão Série A'),
    ('Chapecoense', 'CHA', 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Logo_Associa%C3%A7%C3%A3o_Chapecoense_de_Futebol.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Brasileirão Série A'),
    ('Corinthians', 'COR', 'https://upload.wikimedia.org/wikipedia/en/5/5a/Sport_Club_Corinthians_Paulista_crest.svg?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=original', 'Brasileirão Série A'),
    ('Coritiba', 'CFC', 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Coritiba_Foot_Ball_Club_logo.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Brasileirão Série A'),
    ('Cruzeiro', 'CRU', '', 'Brasileirão Série A'),
    ('Flamengo', 'FLA', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Clube_de_Regatas_do_Flamengo_logo.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Brasileirão Série A'),
    ('Fluminense', 'FLU', 'https://upload.wikimedia.org/wikipedia/commons/1/12/Fluminense_Football_Club.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Brasileirão Série A'),
    ('Grêmio', 'GRE', 'https://upload.wikimedia.org/wikipedia/commons/0/08/Gremio_logo.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Brasileirão Série A'),
    ('Internacional', 'INT', '', 'Brasileirão Série A'),
    ('Mirassol', 'MIR', 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Mirassol_Futebol_Clube_logo_%283_stars%29.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Brasileirão Série A'),
    ('Palmeiras', 'PAL', 'https://upload.wikimedia.org/wikipedia/commons/6/68/Sociedade_Esportiva_Palmeiras_logo_%281_red_star%29.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Brasileirão Série A'),
    ('Red Bull Bragantino', 'RBB', 'https://upload.wikimedia.org/wikipedia/en/2/2e/Red_Bull_Bragantino_logo.svg?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=original', 'Brasileirão Série A'),
    ('Remo', 'REM', '', 'Brasileirão Série A'),
    ('Santos', 'SAN', 'https://upload.wikimedia.org/wikipedia/commons/1/15/Santos_Logo.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Brasileirão Série A'),
    ('São Paulo', 'SAO', '', 'Brasileirão Série A'),
    ('Vasco da Gama', 'VAS', '', 'Brasileirão Série A'),
    ('Vitória', 'VIT', '', 'Brasileirão Série A'),
    ('Augsburg', 'FCA', 'https://upload.wikimedia.org/wikipedia/en/c/c5/FC_Augsburg_logo.svg', 'Bundesliga'),
    ('Bayer Leverkusen', 'B04', 'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg', 'Bundesliga'),
    ('Bayern Munich', 'BAY', 'https://upload.wikimedia.org/wikipedia/commons/8/8d/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg', 'Bundesliga'),
    ('Borussia Dortmund', 'BVB', 'https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg', 'Bundesliga'),
    ('Borussia Mönchengladbach', 'BMG', 'https://upload.wikimedia.org/wikipedia/commons/8/81/Borussia_M%C3%B6nchengladbach_logo.svg', 'Bundesliga'),
    ('Eintracht Frankfurt', 'SGE', 'https://upload.wikimedia.org/wikipedia/en/7/7e/Eintracht_Frankfurt_crest.svg', 'Bundesliga'),
    ('Elversberg', 'SVE', 'https://upload.wikimedia.org/wikipedia/commons/d/d4/SV_Elversberg_Logo_2021.svg', 'Bundesliga'),
    ('Freiburg', 'SCF', 'https://upload.wikimedia.org/wikipedia/en/6/6d/SC_Freiburg_logo.svg', 'Bundesliga'),
    ('Hamburg', 'HSV', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Hamburger_SV_logo.svg', 'Bundesliga'),
    ('Hoffenheim', 'TSG', 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Logo_TSG_Hoffenheim.svg', 'Bundesliga'),
    ('Köln', 'KOE', 'https://upload.wikimedia.org/wikipedia/commons/0/01/1._FC_Koeln_Logo_2014%E2%80%93.svg', 'Bundesliga'),
    ('Mainz', 'M05', 'https://upload.wikimedia.org/wikipedia/commons/1/1b/1._FSV_Mainz_05_logo.svg', 'Bundesliga'),
    ('Paderborn', 'SCP', 'https://upload.wikimedia.org/wikipedia/commons/6/67/SC_Paderborn_07_Logo_new.svg', 'Bundesliga'),
    ('RB Leipzig', 'RBL', 'https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg', 'Bundesliga'),
    ('Schalke', 'S04', 'https://upload.wikimedia.org/wikipedia/commons/6/6d/FC_Schalke_04_Logo.svg', 'Bundesliga'),
    ('Stuttgart', 'VFB', 'https://upload.wikimedia.org/wikipedia/commons/e/eb/VfB_Stuttgart_1893_Logo.svg', 'Bundesliga'),
    ('Union Berlin', 'FCU', 'https://upload.wikimedia.org/wikipedia/commons/4/44/1._FC_Union_Berlin_Logo.svg', 'Bundesliga'),
    ('Werder Bremen', 'SVW', 'https://upload.wikimedia.org/wikipedia/commons/b/be/SV-Werder-Bremen-Logo.svg', 'Bundesliga'),
    ('ADO Den Haag', 'ADO', 'https://upload.wikimedia.org/wikipedia/en/a/ad/ADO_Den_Haag_logo.svg', 'Eredivisie'),
    ('AZ Alkmaar', 'AZ', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/AZ_Alkmaar.svg', 'Eredivisie'),
    ('Ajax', 'AJA', 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Logo_AFC_Ajax_%281928-1991%2C_2025-%29.png', 'Eredivisie'),
    ('Cambuur', 'CAM', 'https://upload.wikimedia.org/wikipedia/en/c/cb/SC_Cambuur_logo.svg', 'Eredivisie'),
    ('Excelsior', 'EXC', 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Excelsior_Rotterdam_logo_2021.svg', 'Eredivisie'),
    ('Feyenoord', 'FEY', 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Feyenoord_logo_since_2024.svg', 'Eredivisie'),
    ('Fortuna Sittard', 'FOR', 'https://upload.wikimedia.org/wikipedia/en/e/ef/Fortuna_Sittard_Logo.svg', 'Eredivisie'),
    ('Go Ahead Eagles', 'GAE', 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Go_Ahead_Eagles_logo.svg', 'Eredivisie'),
    ('Groningen', 'GRO', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/FC_Groningen_logo.svg', 'Eredivisie'),
    ('Heerenveen', 'HEE', 'https://upload.wikimedia.org/wikipedia/en/e/e1/SC_Heerenveen_logo.svg', 'Eredivisie'),
    ('NEC Nijmegen', 'NEC', 'https://upload.wikimedia.org/wikipedia/en/3/38/NEC_Nijmegen_logo.svg', 'Eredivisie'),
    ('PEC Zwolle', 'PEC', 'https://upload.wikimedia.org/wikipedia/en/f/f3/PEC_Zwolle_logo.svg', 'Eredivisie'),
    ('PSV Eindhoven', 'PSV', 'https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven.svg', 'Eredivisie'),
    ('Sparta Rotterdam', 'SPA', 'https://upload.wikimedia.org/wikipedia/en/9/9f/Sparta_Rotterdam_logo.svg', 'Eredivisie'),
    ('Telstar', 'TEL', 'https://upload.wikimedia.org/wikipedia/en/4/4d/SC_Telstar_logo.svg', 'Eredivisie'),
    ('Twente', 'TWE', 'https://upload.wikimedia.org/wikipedia/en/e/e3/FC_Twente.svg', 'Eredivisie'),
    ('Utrecht', 'UTR', 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Logo_FC_Utrecht.svg', 'Eredivisie'),
    ('Willem II', 'WIL', 'https://upload.wikimedia.org/wikipedia/en/7/77/Willem_II_logo.svg', 'Eredivisie'),
    ('Alavés', 'ALA', 'https://upload.wikimedia.org/wikipedia/en/f/f8/Deportivo_Alaves_logo_%282020%29.svg', 'La Liga'),
    ('Athletic Bilbao', 'ATH', 'https://upload.wikimedia.org/wikipedia/en/9/98/Club_Athletic_Bilbao_logo.svg', 'La Liga'),
    ('Atlético Madrid', 'ATM', 'https://upload.wikimedia.org/wikipedia/en/f/f9/Atletico_Madrid_Logo_2024.svg', 'La Liga'),
    ('Barcelona', 'BAR', 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg', 'La Liga'),
    ('Celta Vigo', 'CEL', 'https://upload.wikimedia.org/wikipedia/en/1/12/RC_Celta_de_Vigo_logo.svg', 'La Liga'),
    ('Deportivo La Coruña', 'DEP', 'https://upload.wikimedia.org/wikipedia/en/5/56/RC_Deportivo_A_Coru%C3%B1a_logo_2026.svg', 'La Liga'),
    ('Elche', 'ELC', 'https://upload.wikimedia.org/wikipedia/en/a/a7/Elche_CF_logo.svg', 'La Liga'),
    ('Espanyol', 'ESP', 'https://upload.wikimedia.org/wikipedia/en/9/92/RCD_Espanyol_crest.svg', 'La Liga'),
    ('Getafe', 'GET', 'https://upload.wikimedia.org/wikipedia/en/4/46/Getafe_logo.svg', 'La Liga'),
    ('Levante', 'LEV', 'https://upload.wikimedia.org/wikipedia/en/7/7b/Levante_Uni%C3%B3n_Deportiva%2C_S.A.D._logo.svg', 'La Liga'),
    ('Málaga', 'MAL', 'https://upload.wikimedia.org/wikipedia/en/6/6d/M%C3%A1laga_CF.svg', 'La Liga'),
    ('Osasuna', 'OSA', 'https://upload.wikimedia.org/wikipedia/en/3/38/CA_Osasuna_2024_crest.svg', 'La Liga'),
    ('Racing Santander', 'RAC', 'https://upload.wikimedia.org/wikipedia/en/f/f5/Racing_de_Santander_logo.svg', 'La Liga'),
    ('Rayo Vallecano', 'RAY', 'https://upload.wikimedia.org/wikipedia/en/d/d8/Rayo_Vallecano_logo.svg', 'La Liga'),
    ('Real Betis', 'BET', 'https://upload.wikimedia.org/wikipedia/en/2/2f/Real_Betis_2022_logo.svg', 'La Liga'),
    ('Real Madrid', 'RMA', 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg', 'La Liga'),
    ('Real Sociedad', 'RSO', 'https://upload.wikimedia.org/wikipedia/en/f/f1/Real_Sociedad_logo.svg', 'La Liga'),
    ('Sevilla', 'SEV', 'https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg', 'La Liga'),
    ('Valencia', 'VAL', 'https://upload.wikimedia.org/wikipedia/en/c/ce/Valenciacf.svg', 'La Liga'),
    ('Villarreal', 'VIL', 'https://upload.wikimedia.org/wikipedia/en/b/b9/Villarreal_CF_logo-en.svg', 'La Liga'),
    ('Académico de Viseu', 'ACV', 'https://upload.wikimedia.org/wikipedia/commons/9/9f/A.C._Viseu.svg', 'Liga Portugal'),
    ('Alverca', 'ALV', 'https://upload.wikimedia.org/wikipedia/en/f/f5/F.C._Alverca_logo.svg', 'Liga Portugal'),
    ('Arouca', 'ARO', 'https://upload.wikimedia.org/wikipedia/en/9/9a/F.C._Arouca_logo.svg', 'Liga Portugal'),
    ('Benfica', 'BEN', 'https://upload.wikimedia.org/wikipedia/en/a/a2/SL_Benfica_logo.svg', 'Liga Portugal'),
    ('Braga', 'BRA', 'https://upload.wikimedia.org/wikipedia/en/7/79/S.C._Braga_logo.svg', 'Liga Portugal'),
    ('Casa Pia', 'CPI', 'https://upload.wikimedia.org/wikipedia/en/6/68/Casa_Pia_A.C._logo.svg', 'Liga Portugal'),
    ('Estoril', 'EST', 'https://upload.wikimedia.org/wikipedia/en/9/94/GD_Estoril_Praia_logo.svg', 'Liga Portugal'),
    ('Estrela da Amadora', 'EAM', 'https://upload.wikimedia.org/wikipedia/commons/0/08/S%C3%ADmbolo_Estrela_da_Amadora.svg', 'Liga Portugal'),
    ('Famalicão', 'FAM', 'https://upload.wikimedia.org/wikipedia/en/0/0e/F.C._Famalic%C3%A3o_logo.svg', 'Liga Portugal'),
    ('Gil Vicente', 'GIL', 'https://upload.wikimedia.org/wikipedia/en/6/60/Gil_Vicente_F.C._logo.svg', 'Liga Portugal'),
    ('Marítimo', 'MAR', 'https://upload.wikimedia.org/wikipedia/en/3/30/C.S._Mar%C3%ADtimo_logo.svg', 'Liga Portugal'),
    ('Moreirense', 'MOR', 'https://upload.wikimedia.org/wikipedia/en/1/1b/Moreirense_Futebol_Clube_logo.svg', 'Liga Portugal'),
    ('Nacional', 'NAC', 'https://upload.wikimedia.org/wikipedia/en/9/90/C.D._Nacional_logo.svg', 'Liga Portugal'),
    ('Porto', 'POR', 'https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto.svg', 'Liga Portugal'),
    ('Rio Ave', 'RIO', 'https://upload.wikimedia.org/wikipedia/en/0/0c/Rio_Ave_FC_logo.svg', 'Liga Portugal'),
    ('Santa Clara', 'STC', 'https://upload.wikimedia.org/wikipedia/en/3/37/C.D._Santa_Clara_logo.svg', 'Liga Portugal'),
    ('Sporting CP', 'SCP', 'https://upload.wikimedia.org/wikipedia/en/9/97/Sporting_Clube_de_Portugal_logo_%282026%29.svg', 'Liga Portugal'),
    ('Vitória de Guimarães', 'VSC', 'https://upload.wikimedia.org/wikipedia/en/d/d5/Vit%C3%B3ria_Guimar%C3%A3es.svg', 'Liga Portugal'),
    ('Angers', 'ANG', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Angers_Sporting_Club_de_l%27Ouest_logo.svg', 'Ligue 1'),
    ('Auxerre', 'AUX', 'https://upload.wikimedia.org/wikipedia/en/5/51/AJAuxerreLogo.svg', 'Ligue 1'),
    ('Brest', 'BRE', 'https://upload.wikimedia.org/wikipedia/en/0/05/Stade_Brestois_29_logo.svg', 'Ligue 1'),
    ('Le Havre', 'HAC', 'https://upload.wikimedia.org/wikipedia/en/f/fc/Le_Havre_AC_logo.svg', 'Ligue 1'),
    ('Le Mans', 'LEM', 'https://upload.wikimedia.org/wikipedia/en/5/57/Le_Mans_FC_logo.svg', 'Ligue 1'),
    ('Lens', 'RCL', 'https://upload.wikimedia.org/wikipedia/en/c/cc/RC_Lens_logo.svg', 'Ligue 1'),
    ('Lille', 'LIL', 'https://upload.wikimedia.org/wikipedia/en/3/3f/Lille_OSC_2018_logo.svg', 'Ligue 1'),
    ('Lorient', 'LOR', 'https://upload.wikimedia.org/wikipedia/en/4/4c/FC_Lorient_logo.svg', 'Ligue 1'),
    ('Lyon', 'OL', 'https://upload.wikimedia.org/wikipedia/en/1/1c/Olympique_Lyonnais_logo.svg', 'Ligue 1'),
    ('Marseille', 'OM', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Olympique_de_Marseille_2026_logo.svg', 'Ligue 1'),
    ('Monaco', 'ASM', 'https://upload.wikimedia.org/wikipedia/en/c/cf/LogoASMonacoFC2021.svg', 'Ligue 1'),
    ('Nice', 'NIC', 'https://upload.wikimedia.org/wikipedia/en/2/2e/OGC_Nice_logo.svg', 'Ligue 1'),
    ('Paris FC', 'PFC', 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Paris_FCLogo_11-24.png', 'Ligue 1'),
    ('Paris Saint-Germain', 'PSG', 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg', 'Ligue 1'),
    ('Rennes', 'REN', 'https://upload.wikimedia.org/wikipedia/en/9/9e/Stade_Rennais_FC.svg', 'Ligue 1'),
    ('Strasbourg', 'RCS', 'https://upload.wikimedia.org/wikipedia/en/8/80/Racing_Club_de_Strasbourg_logo.svg', 'Ligue 1'),
    ('Toulouse', 'TFC', 'https://upload.wikimedia.org/wikipedia/en/6/63/Toulouse_FC_2018_logo.svg', 'Ligue 1'),
    ('Troyes', 'TRO', 'https://upload.wikimedia.org/wikipedia/commons/a/a9/ESTAC_Troyes_Logo.svg', 'Ligue 1'),
    ('Atlanta United', 'ATL', 'https://upload.wikimedia.org/wikipedia/en/b/bb/Atlanta_MLS.svg', 'Major League Soccer'),
    ('Austin FC', 'ATX', 'https://upload.wikimedia.org/wikipedia/en/8/85/Austin_FC_logo.svg', 'Major League Soccer'),
    ('CF Montréal', 'MTL', 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Logo_of_CF_Montreal_2023.svg', 'Major League Soccer'),
    ('Charlotte FC', 'CLT', 'https://upload.wikimedia.org/wikipedia/en/9/91/Charlotte_FC_logo.svg', 'Major League Soccer'),
    ('Chicago Fire', 'CHI', 'https://upload.wikimedia.org/wikipedia/commons/0/03/Chicago_Fire_logo%2C_2021.svg', 'Major League Soccer'),
    ('Colorado Rapids', 'COL', 'https://upload.wikimedia.org/wikipedia/en/2/2b/Colorado_Rapids_logo.svg', 'Major League Soccer'),
    ('Columbus Crew', 'CLB', 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Columbus_Crew_logo_2021.svg', 'Major League Soccer'),
    ('D.C. United', 'DC', 'https://upload.wikimedia.org/wikipedia/en/3/32/D.C._United_logo_%282016%29.svg', 'Major League Soccer'),
    ('FC Cincinnati', 'CIN', 'https://upload.wikimedia.org/wikipedia/en/7/78/FC_Cincinnati_primary_logo_2018.svg', 'Major League Soccer'),
    ('FC Dallas', 'DAL', 'https://upload.wikimedia.org/wikipedia/en/c/c9/FC_Dallas_logo.svg', 'Major League Soccer'),
    ('Houston Dynamo', 'HOU', 'https://upload.wikimedia.org/wikipedia/commons/6/66/Houston_Dynamo_FC_logo.svg', 'Major League Soccer'),
    ('Inter Miami', 'MIA', 'https://upload.wikimedia.org/wikipedia/en/5/5c/Inter_Miami_CF_logo.svg', 'Major League Soccer'),
    ('LA Galaxy', 'LA', 'https://upload.wikimedia.org/wikipedia/commons/7/70/Los_Angeles_Galaxy_logo.svg', 'Major League Soccer'),
    ('Los Angeles FC', 'LAFC', 'https://upload.wikimedia.org/wikipedia/commons/8/86/Los_Angeles_Football_Club.svg', 'Major League Soccer'),
    ('Minnesota United', 'MIN', 'https://upload.wikimedia.org/wikipedia/en/e/e8/Minnesota_United_FC_%28MLS%29_Primary_logo.svg', 'Major League Soccer'),
    ('Nashville SC', 'NSH', 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Nashville_SC_logo%2C_2020.svg', 'Major League Soccer'),
    ('New England Revolution', 'NE', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Logo_of_New_England_Revolution_%282021%29.svg', 'Major League Soccer'),
    ('New York City FC', 'NYC', '', 'Major League Soccer'),
    ('New York Red Bulls', 'RBNY', 'https://upload.wikimedia.org/wikipedia/en/5/51/New_York_Red_Bulls_logo.svg', 'Major League Soccer'),
    ('Orlando City', 'ORL', 'https://upload.wikimedia.org/wikipedia/en/6/6a/Orlando_City_2014.svg', 'Major League Soccer'),
    ('Philadelphia Union', 'PHI', 'https://upload.wikimedia.org/wikipedia/en/4/46/Philadelphia_Union_2018_logo.svg', 'Major League Soccer'),
    ('Portland Timbers', 'POR', '', 'Major League Soccer'),
    ('Real Salt Lake', 'RSL', 'https://upload.wikimedia.org/wikipedia/en/5/54/Real_Salt_Lake_2010.svg?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=original', 'Major League Soccer'),
    ('San Diego FC', 'SD', 'https://upload.wikimedia.org/wikipedia/en/6/6f/San_Diego_FC_logo.svg?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=original', 'Major League Soccer'),
    ('San Jose Earthquakes', 'SJ', 'https://upload.wikimedia.org/wikipedia/en/9/98/San_Jose_Earthquakes_2014.svg?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=original', 'Major League Soccer'),
    ('Seattle Sounders', 'SEA', 'https://upload.wikimedia.org/wikipedia/en/8/84/Seattle_Sounders_logo.svg?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=original', 'Major League Soccer'),
    ('Sporting Kansas City', 'SKC', '', 'Major League Soccer'),
    ('St. Louis City', 'STL', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Logo_of_St._Louis_City_SC.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Major League Soccer'),
    ('Toronto FC', 'TOR', 'https://upload.wikimedia.org/wikipedia/en/7/7c/Toronto_FC_Logo.svg?utm_source=en.wikipedia.org&utm_campaign=imageinfo&utm_content=original', 'Major League Soccer'),
    ('Vancouver Whitecaps', 'VAN', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Vancouver_Whitecaps_logo.svg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=original', 'Major League Soccer'),
    ('Arsenal', 'ARS', 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg', 'Premier League'),
    ('Aston Villa', 'AVL', 'https://upload.wikimedia.org/wikipedia/en/9/9a/Aston_Villa_FC_new_crest.svg', 'Premier League'),
    ('Bournemouth', 'BOU', 'https://upload.wikimedia.org/wikipedia/en/e/e5/AFC_Bournemouth_%282013%29.svg', 'Premier League'),
    ('Brentford', 'BRE', 'https://upload.wikimedia.org/wikipedia/en/2/2a/Brentford_FC_crest.svg', 'Premier League'),
    ('Brighton & Hove Albion', 'BHA', 'https://upload.wikimedia.org/wikipedia/en/d/d0/Brighton_and_Hove_Albion_FC_crest.svg', 'Premier League'),
    ('Chelsea', 'CHE', 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg', 'Premier League'),
    ('Coventry City', 'COV', 'https://upload.wikimedia.org/wikipedia/en/7/7b/Coventry_City_FC_crest.svg', 'Premier League'),
    ('Crystal Palace', 'CRY', 'https://upload.wikimedia.org/wikipedia/en/a/a2/Crystal_Palace_FC_logo_%282022%29.svg', 'Premier League'),
    ('Everton', 'EVE', 'https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg', 'Premier League'),
    ('Fulham', 'FUL', 'https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg', 'Premier League'),
    ('Hull City', 'HUL', 'https://upload.wikimedia.org/wikipedia/en/5/54/Hull_City_A.F.C._logo.svg', 'Premier League'),
    ('Ipswich Town', 'IPS', 'https://upload.wikimedia.org/wikipedia/en/4/43/Ipswich_Town.svg', 'Premier League'),
    ('Leeds United', 'LEE', 'https://upload.wikimedia.org/wikipedia/en/5/54/Leeds_United_F.C._logo.svg', 'Premier League'),
    ('Liverpool', 'LIV', 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg', 'Premier League'),
    ('Manchester City', 'MCI', 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg', 'Premier League'),
    ('Manchester United', 'MUN', 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg', 'Premier League'),
    ('Newcastle United', 'NEW', 'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg', 'Premier League'),
    ('Nottingham Forest', 'NFO', 'https://upload.wikimedia.org/wikipedia/en/e/e5/Nottingham_Forest_F.C._logo.svg', 'Premier League'),
    ('Sunderland', 'SUN', 'https://upload.wikimedia.org/wikipedia/en/7/77/Logo_Sunderland.svg', 'Premier League'),
    ('Tottenham Hotspur', 'TOT', 'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg', 'Premier League'),
    ('Abha', 'ABH', 'https://upload.wikimedia.org/wikipedia/en/7/76/Abha_Club_Logo.svg', 'Saudi Pro League'),
    ('Al-Ahli', 'AHL', 'https://upload.wikimedia.org/wikipedia/en/4/45/Al_Ahli_Saudi_FC_logo.svg', 'Saudi Pro League'),
    ('Al-Diriyah', 'DIR', 'https://upload.wikimedia.org/wikipedia/en/3/32/Diriyah_Club_Logo.svg', 'Saudi Pro League'),
    ('Al-Ettifaq', 'ETT', 'https://upload.wikimedia.org/wikipedia/en/3/34/Al-Ettifaq_FC_logo.svg', 'Saudi Pro League'),
    ('Al-Faisaly', 'FAI', 'https://upload.wikimedia.org/wikipedia/en/c/c9/Al-Faisaly_FC_New_Logo.png', 'Saudi Pro League'),
    ('Al-Fateh', 'FAT', '', 'Saudi Pro League'),
    ('Al-Fayha', 'FAY', 'https://upload.wikimedia.org/wikipedia/en/0/0f/Al-Fayha_FC.svg', 'Saudi Pro League'),
    ('Al-Hazem', 'HAZ', 'https://upload.wikimedia.org/wikipedia/en/a/ab/Al-Hazem_FC_Logo.svg', 'Saudi Pro League'),
    ('Al-Hilal', 'HIL', 'https://upload.wikimedia.org/wikipedia/commons/5/55/Al_Hilal_SFC_Logo.svg', 'Saudi Pro League'),
    ('Al-Ittihad', 'ITT', 'https://upload.wikimedia.org/wikipedia/en/8/87/Al-Ittihad_Club_%28Jeddah%29_logo.svg', 'Saudi Pro League'),
    ('Al-Khaleej', 'KHA', 'https://upload.wikimedia.org/wikipedia/en/3/32/Al-Khaleej_FC_Logo.svg', 'Saudi Pro League'),
    ('Al-Kholood', 'KHO', 'https://upload.wikimedia.org/wikipedia/en/b/b6/Al_Kholood_Club_Logo.svg', 'Saudi Pro League'),
    ('Al-Nassr', 'NAS', 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Nassr_FC_Logo.svg', 'Saudi Pro League'),
    ('Al-Qadsiah', 'QAD', 'https://upload.wikimedia.org/wikipedia/commons/6/68/QAD_LOGO.png', 'Saudi Pro League'),
    ('Al-Riyadh', 'RIY', 'https://upload.wikimedia.org/wikipedia/en/3/39/Al-Riyadh_SC.svg', 'Saudi Pro League'),
    ('Al-Shabab', 'SHA', 'https://upload.wikimedia.org/wikipedia/en/2/2d/Al_Shabab_FC_%28Riyadh%29.svg', 'Saudi Pro League'),
    ('Al-Taawoun', 'TAA', 'https://upload.wikimedia.org/wikipedia/en/0/08/Al_Taawoun_FC_Logo.svg', 'Saudi Pro League'),
    ('Neom', 'NEO', 'https://upload.wikimedia.org/wikipedia/en/4/4a/Neom_SC_Logo.png', 'Saudi Pro League'),
    ('Aberdeen', 'ABE', 'https://upload.wikimedia.org/wikipedia/en/f/fb/Aberdeen_FC_stars_crest.svg', 'Scottish Premiership'),
    ('Celtic', 'CEL', 'https://upload.wikimedia.org/wikipedia/en/7/71/Celtic_FC_crest.svg', 'Scottish Premiership'),
    ('Dundee', 'DUN', 'https://upload.wikimedia.org/wikipedia/en/3/3b/Dundee_FC_2025_Crest.svg', 'Scottish Premiership'),
    ('Dundee United', 'DDU', 'https://upload.wikimedia.org/wikipedia/en/b/bf/Dundee_United_FC_crest.svg', 'Scottish Premiership'),
    ('Falkirk', 'FAL', 'https://upload.wikimedia.org/wikipedia/en/5/5d/Falkirk_FC_logo.svg', 'Scottish Premiership'),
    ('Heart of Midlothian', 'HEA', 'https://upload.wikimedia.org/wikipedia/en/6/61/Heart_of_Midlothian_FC_logo.svg', 'Scottish Premiership'),
    ('Hibernian', 'HIB', 'https://upload.wikimedia.org/wikipedia/en/0/03/Hibernian_FC_2026_crest.svg', 'Scottish Premiership'),
    ('Kilmarnock', 'KIL', 'https://upload.wikimedia.org/wikipedia/en/3/38/Kilmarnock_FC_crest.svg', 'Scottish Premiership'),
    ('Motherwell', 'MOT', 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Motherwell_FC_crest.svg', 'Scottish Premiership'),
    ('Rangers', 'RAN', 'https://upload.wikimedia.org/wikipedia/en/4/43/Rangers_FC.svg', 'Scottish Premiership'),
    ('St Johnstone', 'SJN', 'https://upload.wikimedia.org/wikipedia/en/4/40/St_Johnstone_FC_crest.svg', 'Scottish Premiership'),
    ('St Mirren', 'STM', 'https://upload.wikimedia.org/wikipedia/en/2/27/St_Mirren_FC_crest.svg', 'Scottish Premiership'),
    ('AC Milan', 'MIL', 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg', 'Serie A'),
    ('Atalanta', 'ATA', 'https://upload.wikimedia.org/wikipedia/en/f/f2/Atalanta_BC_new_logo.svg', 'Serie A'),
    ('Bologna', 'BOL', 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Bologna_F.C._1909_logo.svg', 'Serie A'),
    ('Cagliari', 'CAG', 'https://upload.wikimedia.org/wikipedia/en/6/61/Cagliari_Calcio_1920.svg', 'Serie A'),
    ('Como', 'COM', 'https://upload.wikimedia.org/wikipedia/commons/9/99/Calcio_Como_-_logo_%28Italy%2C_2019-%29.svg', 'Serie A'),
    ('Fiorentina', 'FIO', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/ACF_Fiorentina_-_logo_%28Italy%2C_2022%29.svg', 'Serie A'),
    ('Frosinone', 'FRO', 'https://upload.wikimedia.org/wikipedia/en/0/0b/Frosinone_Calcio_logo.svg', 'Serie A'),
    ('Genoa', 'GEN', 'https://upload.wikimedia.org/wikipedia/en/2/2c/Genoa_CFC_crest.svg', 'Serie A'),
    ('Inter Milan', 'INT', 'https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg', 'Serie A'),
    ('Juventus', 'JUV', 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Juventus_FC_-_logo_black_%28Italy%2C_2020%29.svg', 'Serie A'),
    ('Lazio', 'LAZ', 'https://upload.wikimedia.org/wikipedia/en/c/ce/S.S._Lazio_badge.svg', 'Serie A'),
    ('Lecce', 'LEC', 'https://upload.wikimedia.org/wikipedia/en/2/23/US_Lecce_crest.svg', 'Serie A'),
    ('Monza', 'MON', 'https://upload.wikimedia.org/wikipedia/en/a/a7/AC_Monza_logo_%282021%29.svg', 'Serie A'),
    ('Napoli', 'NAP', 'https://upload.wikimedia.org/wikipedia/commons/4/4d/SSC_Napoli_2025_%28white_and_azure%29.svg', 'Serie A'),
    ('Parma', 'PAR', 'https://upload.wikimedia.org/wikipedia/commons/9/97/Logo_Parma_Calcio_1913_%28adozione_2016%29.svg', 'Serie A'),
    ('Roma', 'ROM', 'https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg', 'Serie A'),
    ('Sassuolo', 'SAS', 'https://upload.wikimedia.org/wikipedia/en/1/1c/US_Sassuolo_Calcio_logo.svg', 'Serie A'),
    ('Torino', 'TOR', 'https://upload.wikimedia.org/wikipedia/en/2/2e/Torino_FC_Logo.svg', 'Serie A'),
    ('Udinese', 'UDI', 'https://upload.wikimedia.org/wikipedia/en/c/ce/Udinese_Calcio_logo.svg', 'Serie A'),
    ('Venezia', 'VEN', 'https://upload.wikimedia.org/wikipedia/en/3/39/Venezia_FC_crest.svg', 'Serie A')
) AS c(name, short_name, crest_url, league)
JOIN leagues l ON lower(l.name) = lower(c.league)
ON CONFLICT (lower(name)) DO UPDATE
SET name = EXCLUDED.name,
    short_name = EXCLUDED.short_name,
    crest_url = COALESCE(EXCLUDED.crest_url, clubs.crest_url),
    league_id = EXCLUDED.league_id;

UPDATE clubs SET league_id = NULL
WHERE league_id IN (
    SELECT l.id FROM leagues l
    JOIN (VALUES
        ('Argentine Primera División'),
        ('Brasileirão Série A'),
        ('Bundesliga'),
        ('Eredivisie'),
        ('La Liga'),
        ('Liga Portugal'),
        ('Ligue 1'),
        ('Major League Soccer'),
        ('Premier League'),
        ('Saudi Pro League'),
        ('Scottish Premiership'),
        ('Serie A')
    ) AS r(name) ON lower(l.name) = lower(r.name)
)
AND lower(name) NOT IN (
    SELECT lower(r.name) FROM (VALUES
        ('Aldosivi'),
        ('Argentinos Juniors'),
        ('Atlético Tucumán'),
        ('Banfield'),
        ('Barracas Central'),
        ('Belgrano'),
        ('Boca Juniors'),
        ('Central Córdoba'),
        ('Defensa y Justicia'),
        ('Deportivo Riestra'),
        ('Estudiantes'),
        ('Estudiantes de Río Cuarto'),
        ('Gimnasia y Esgrima La Plata'),
        ('Gimnasia y Esgrima de Mendoza'),
        ('Huracán'),
        ('Independiente'),
        ('Independiente Rivadavia'),
        ('Instituto'),
        ('Lanús'),
        ('Newell''s Old Boys'),
        ('Platense'),
        ('Racing Club'),
        ('River Plate'),
        ('Rosario Central'),
        ('San Lorenzo'),
        ('Sarmiento'),
        ('Talleres'),
        ('Tigre'),
        ('Unión'),
        ('Vélez Sarsfield'),
        ('Athletico Paranaense'),
        ('Atlético Mineiro'),
        ('Bahia'),
        ('Botafogo'),
        ('Chapecoense'),
        ('Corinthians'),
        ('Coritiba'),
        ('Cruzeiro'),
        ('Flamengo'),
        ('Fluminense'),
        ('Grêmio'),
        ('Internacional'),
        ('Mirassol'),
        ('Palmeiras'),
        ('Red Bull Bragantino'),
        ('Remo'),
        ('Santos'),
        ('São Paulo'),
        ('Vasco da Gama'),
        ('Vitória'),
        ('Augsburg'),
        ('Bayer Leverkusen'),
        ('Bayern Munich'),
        ('Borussia Dortmund'),
        ('Borussia Mönchengladbach'),
        ('Eintracht Frankfurt'),
        ('Elversberg'),
        ('Freiburg'),
        ('Hamburg'),
        ('Hoffenheim'),
        ('Köln'),
        ('Mainz'),
        ('Paderborn'),
        ('RB Leipzig'),
        ('Schalke'),
        ('Stuttgart'),
        ('Union Berlin'),
        ('Werder Bremen'),
        ('ADO Den Haag'),
        ('AZ Alkmaar'),
        ('Ajax'),
        ('Cambuur'),
        ('Excelsior'),
        ('Feyenoord'),
        ('Fortuna Sittard'),
        ('Go Ahead Eagles'),
        ('Groningen'),
        ('Heerenveen'),
        ('NEC Nijmegen'),
        ('PEC Zwolle'),
        ('PSV Eindhoven'),
        ('Sparta Rotterdam'),
        ('Telstar'),
        ('Twente'),
        ('Utrecht'),
        ('Willem II'),
        ('Alavés'),
        ('Athletic Bilbao'),
        ('Atlético Madrid'),
        ('Barcelona'),
        ('Celta Vigo'),
        ('Deportivo La Coruña'),
        ('Elche'),
        ('Espanyol'),
        ('Getafe'),
        ('Levante'),
        ('Málaga'),
        ('Osasuna'),
        ('Racing Santander'),
        ('Rayo Vallecano'),
        ('Real Betis'),
        ('Real Madrid'),
        ('Real Sociedad'),
        ('Sevilla'),
        ('Valencia'),
        ('Villarreal'),
        ('Académico de Viseu'),
        ('Alverca'),
        ('Arouca'),
        ('Benfica'),
        ('Braga'),
        ('Casa Pia'),
        ('Estoril'),
        ('Estrela da Amadora'),
        ('Famalicão'),
        ('Gil Vicente'),
        ('Marítimo'),
        ('Moreirense'),
        ('Nacional'),
        ('Porto'),
        ('Rio Ave'),
        ('Santa Clara'),
        ('Sporting CP'),
        ('Vitória de Guimarães'),
        ('Angers'),
        ('Auxerre'),
        ('Brest'),
        ('Le Havre'),
        ('Le Mans'),
        ('Lens'),
        ('Lille'),
        ('Lorient'),
        ('Lyon'),
        ('Marseille'),
        ('Monaco'),
        ('Nice'),
        ('Paris FC'),
        ('Paris Saint-Germain'),
        ('Rennes'),
        ('Strasbourg'),
        ('Toulouse'),
        ('Troyes'),
        ('Atlanta United'),
        ('Austin FC'),
        ('CF Montréal'),
        ('Charlotte FC'),
        ('Chicago Fire'),
        ('Colorado Rapids'),
        ('Columbus Crew'),
        ('D.C. United'),
        ('FC Cincinnati'),
        ('FC Dallas'),
        ('Houston Dynamo'),
        ('Inter Miami'),
        ('LA Galaxy'),
        ('Los Angeles FC'),
        ('Minnesota United'),
        ('Nashville SC'),
        ('New England Revolution'),
        ('New York City FC'),
        ('New York Red Bulls'),
        ('Orlando City'),
        ('Philadelphia Union'),
        ('Portland Timbers'),
        ('Real Salt Lake'),
        ('San Diego FC'),
        ('San Jose Earthquakes'),
        ('Seattle Sounders'),
        ('Sporting Kansas City'),
        ('St. Louis City'),
        ('Toronto FC'),
        ('Vancouver Whitecaps'),
        ('Arsenal'),
        ('Aston Villa'),
        ('Bournemouth'),
        ('Brentford'),
        ('Brighton & Hove Albion'),
        ('Chelsea'),
        ('Coventry City'),
        ('Crystal Palace'),
        ('Everton'),
        ('Fulham'),
        ('Hull City'),
        ('Ipswich Town'),
        ('Leeds United'),
        ('Liverpool'),
        ('Manchester City'),
        ('Manchester United'),
        ('Newcastle United'),
        ('Nottingham Forest'),
        ('Sunderland'),
        ('Tottenham Hotspur'),
        ('Abha'),
        ('Al-Ahli'),
        ('Al-Diriyah'),
        ('Al-Ettifaq'),
        ('Al-Faisaly'),
        ('Al-Fateh'),
        ('Al-Fayha'),
        ('Al-Hazem'),
        ('Al-Hilal'),
        ('Al-Ittihad'),
        ('Al-Khaleej'),
        ('Al-Kholood'),
        ('Al-Nassr'),
        ('Al-Qadsiah'),
        ('Al-Riyadh'),
        ('Al-Shabab'),
        ('Al-Taawoun'),
        ('Neom'),
        ('Aberdeen'),
        ('Celtic'),
        ('Dundee'),
        ('Dundee United'),
        ('Falkirk'),
        ('Heart of Midlothian'),
        ('Hibernian'),
        ('Kilmarnock'),
        ('Motherwell'),
        ('Rangers'),
        ('St Johnstone'),
        ('St Mirren'),
        ('AC Milan'),
        ('Atalanta'),
        ('Bologna'),
        ('Cagliari'),
        ('Como'),
        ('Fiorentina'),
        ('Frosinone'),
        ('Genoa'),
        ('Inter Milan'),
        ('Juventus'),
        ('Lazio'),
        ('Lecce'),
        ('Monza'),
        ('Napoli'),
        ('Parma'),
        ('Roma'),
        ('Sassuolo'),
        ('Torino'),
        ('Udinese'),
        ('Venezia')
    ) AS r(name)
);

-- Real RSS feed URLs, verified reachable and well-formed as of 2026-07-28.
-- talkSPORT and The Athletic have no public RSS feed (both now serve a JS
-- SPA shell at every guessed /feed path; The Athletic is also paywalled) —
-- left NULL until/unless one turns up. Fabrizio Romano has no standalone
-- feed of his own; CaughtOffside republishes his exclusives and is used as
-- a proxy source for his reporting.
INSERT INTO sources (name, feed_url) VALUES
    ('Sky Sports', 'https://www.skysports.com/rss/12040'),
    ('BBC Sport', 'https://feeds.bbci.co.uk/sport/football/rss.xml'),
    ('The Athletic', NULL),
    ('The Guardian Football', 'https://www.theguardian.com/football/rss'),
    ('Daily Mail Sport', 'https://www.dailymail.co.uk/sport/index.rss'),
    ('The Mirror Football', 'https://www.mirror.co.uk/sport/football/rss.xml'),
    ('talkSPORT', NULL),
    ('Football Insider', 'https://www.footballinsider247.com/feed/'),
    ('GiveMeSport', 'https://www.givemesport.com/feed/'),
    ('Fabrizio Romano', 'https://www.caughtoffside.com/feed/')
ON CONFLICT (name) DO UPDATE SET feed_url = EXCLUDED.feed_url;
